-- Viral+ / Edit+ shared core.
-- Source-controlled DDL. Apply through a Supabase migration once database write access is available.
-- This file is intentionally non-destructive.

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  module text not null default 'shared' check (module in ('shared','viralplus','editplus')),
  kind text not null default 'source' check (kind in ('source','render','broll','thumbnail','audio')),
  storage_bucket text not null default 'viralplus-videos',
  storage_path text not null,
  original_name text,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  sha256 text check (sha256 is null or sha256 ~ '^[0-9a-f]{64}$'),
  status text not null default 'uploaded' check (status in ('uploading','uploaded','processing','ready','failed','deleted')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (storage_bucket, storage_path),
  check (split_part(storage_path,'/',1) = user_id::text)
);
create index if not exists media_assets_user_created_idx on public.media_assets(user_id, created_at desc);
create index if not exists media_assets_sha_idx on public.media_assets(user_id, sha256) where sha256 is not null;
alter table public.media_assets enable row level security;
create policy media_assets_select_own on public.media_assets for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.media_assets from anon;
grant select on public.media_assets to authenticated;

create table if not exists public.processing_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('viral_analysis','edit_render')),
  video_id uuid not null references public.media_assets(id) on delete cascade,
  output_video_id uuid references public.media_assets(id) on delete set null,
  status text not null default 'queued' check (
    status in ('uploaded','queued','processing','transcribing','analyzing','generating_report','planning','rendering','encoding','completed','failed','cancelled')
  ),
  progress smallint not null default 0 check (progress between 0 and 100),
  stage text,
  priority smallint not null default 100 check (priority between 0 and 1000),
  idempotency_key text,
  retry_count smallint not null default 0 check (retry_count >= 0),
  max_retries smallint not null default 3 check (max_retries between 0 and 20),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  heartbeat_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  error_code text,
  error text,
  credit_consumed boolean not null default false,
  credit_refunded_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  result jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists processing_jobs_idempotency_idx
  on public.processing_jobs(user_id, idempotency_key) where idempotency_key is not null;
create index if not exists processing_jobs_worker_queue_idx
  on public.processing_jobs(priority, next_attempt_at, created_at)
  where status in ('queued','failed');
create index if not exists processing_jobs_user_created_idx on public.processing_jobs(user_id, created_at desc);
create index if not exists processing_jobs_video_idx on public.processing_jobs(video_id, created_at desc);
alter table public.processing_jobs enable row level security;
create policy processing_jobs_select_own on public.processing_jobs for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.processing_jobs from anon;
grant select on public.processing_jobs to authenticated;

create table if not exists public.job_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.processing_jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null,
  progress smallint check (progress is null or progress between 0 and 100),
  message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists job_events_job_created_idx on public.job_events(job_id, created_at);
create index if not exists job_events_user_created_idx on public.job_events(user_id, created_at desc);
alter table public.job_events enable row level security;
create policy job_events_select_own on public.job_events for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.job_events from anon;
grant select on public.job_events to authenticated;

create table if not exists public.edit_projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source_video_id uuid not null references public.media_assets(id) on delete cascade,
  source_analysis_id uuid references public.viralplus_analyses(id) on delete set null,
  style text not null default 'creator_clean' check (style in ('creator_clean','codie','business_viral','podcast_authority')),
  caption_preset text not null default 'modern_bold' check (caption_preset in ('modern_bold','minimal','creator','karaoke','authority','ugc')),
  status text not null default 'draft' check (status in ('draft','planning','ready','rendering','completed','failed','archived')),
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists edit_projects_user_created_idx on public.edit_projects(user_id, created_at desc);
alter table public.edit_projects enable row level security;
create policy edit_projects_select_own on public.edit_projects for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.edit_projects from anon;
grant select on public.edit_projects to authenticated;

create table if not exists public.edit_timelines (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.edit_projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  version integer not null default 1 check (version > 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  timeline_json jsonb not null,
  decision_model text,
  created_at timestamptz not null default now(),
  unique (project_id, version)
);
create index if not exists edit_timelines_user_created_idx on public.edit_timelines(user_id, created_at desc);
alter table public.edit_timelines enable row level security;
create policy edit_timelines_select_own on public.edit_timelines for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.edit_timelines from anon;
grant select on public.edit_timelines to authenticated;

create table if not exists public.edit_exports (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.edit_projects(id) on delete cascade,
  job_id uuid references public.processing_jobs(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  output_video_id uuid not null references public.media_assets(id) on delete restrict,
  preset text not null default '1080x1920',
  status text not null default 'ready' check (status in ('ready','expired','deleted')),
  created_at timestamptz not null default now()
);
create index if not exists edit_exports_user_created_idx on public.edit_exports(user_id, created_at desc);
alter table public.edit_exports enable row level security;
create policy edit_exports_select_own on public.edit_exports for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.edit_exports from anon;
grant select on public.edit_exports to authenticated;

create table if not exists public.billing_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'stripe' check (provider = 'stripe'),
  plan text not null default 'free' check (plan in ('free','creator','pro')),
  status text not null default 'inactive' check (status in ('inactive','trialing','active','past_due','canceled','unpaid','paused')),
  provider_customer_id text,
  provider_subscription_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists billing_subscriptions_user_provider_idx on public.billing_subscriptions(user_id, provider);
create unique index if not exists billing_subscriptions_provider_sub_idx on public.billing_subscriptions(provider_subscription_id) where provider_subscription_id is not null;
alter table public.billing_subscriptions enable row level security;
create policy billing_subscriptions_select_own on public.billing_subscriptions for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.billing_subscriptions from anon;
grant select on public.billing_subscriptions to authenticated;

create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module text not null check (module in ('viralplus','editplus','shared')),
  units integer not null check (units <> 0),
  reason text not null,
  idempotency_key text,
  job_id uuid references public.processing_jobs(id) on delete set null,
  external_ref text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create unique index if not exists credit_ledger_idempotency_idx
  on public.credit_ledger(user_id, idempotency_key) where idempotency_key is not null;
create index if not exists credit_ledger_user_created_idx on public.credit_ledger(user_id, created_at desc);
alter table public.credit_ledger enable row level security;
create policy credit_ledger_select_own on public.credit_ledger for select to authenticated using ((select auth.uid()) = user_id);
revoke all on public.credit_ledger from anon;
grant select on public.credit_ledger to authenticated;

alter table public.viralplus_analyses
  add column if not exists video_id uuid references public.media_assets(id) on delete set null,
  add column if not exists job_id uuid references public.processing_jobs(id) on delete set null;
create index if not exists viralplus_analyses_video_id_idx on public.viralplus_analyses(video_id) where video_id is not null;
create index if not exists viralplus_analyses_job_id_idx on public.viralplus_analyses(job_id) where job_id is not null;

create or replace view public.analysis_jobs with (security_invoker = true) as
select id,user_id,video_id,output_video_id,status,progress,stage,created_at,started_at,completed_at,error,retry_count,max_retries,next_attempt_at,locked_at,locked_by,heartbeat_at,payload,result
from public.processing_jobs where kind='viral_analysis';

create or replace view public.edit_jobs with (security_invoker = true) as
select id,user_id,video_id,output_video_id,status,progress,stage,created_at,started_at,completed_at,error,retry_count,max_retries,next_attempt_at,locked_at,locked_by,heartbeat_at,payload,result
from public.processing_jobs where kind='edit_render';

revoke all on public.analysis_jobs from anon;
revoke all on public.edit_jobs from anon;
grant select on public.analysis_jobs to authenticated;
grant select on public.edit_jobs to authenticated;

create or replace function public.claim_processing_job(p_worker_id text)
returns setof public.processing_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidate as (
    select id
    from public.processing_jobs
    where next_attempt_at <= now()
      and (
        status='queued'
        or (status='failed' and retry_count < max_retries)
        or (
          status in ('processing','transcribing','analyzing','generating_report','planning','rendering','encoding')
          and heartbeat_at < now() - interval '10 minutes'
        )
      )
    order by priority asc, created_at asc
    for update skip locked
    limit 1
  )
  update public.processing_jobs j
  set status='processing',
      progress=greatest(j.progress,1),
      stage='claimed',
      locked_at=now(),
      locked_by=p_worker_id,
      heartbeat_at=now(),
      started_at=coalesce(j.started_at,now()),
      error_code=null,
      error=null,
      updated_at=now()
  from candidate
  where j.id=candidate.id
  returning j.*;
end;
$$;
revoke all on function public.claim_processing_job(text) from public, anon, authenticated;
grant execute on function public.claim_processing_job(text) to service_role;

create or replace function public.refund_job_credit(p_job_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  j public.processing_jobs%rowtype;
begin
  select * into j from public.processing_jobs where id=p_job_id for update;
  if not found or not j.credit_consumed or j.credit_refunded_at is not null then return false; end if;

  update public.viralplus_profiles
  set analyses_used=greatest(analyses_used-1,0), updated_at=now()
  where user_id=j.user_id;

  update public.processing_jobs
  set credit_refunded_at=now(), updated_at=now()
  where id=p_job_id;

  return true;
end;
$$;
revoke all on function public.refund_job_credit(uuid) from public, anon, authenticated;
grant execute on function public.refund_job_credit(uuid) to service_role;
